### ISSUE TITLE
[Feature Request] Add keyboard shortcuts to switch between accounts

### ISSUE THREAD

**Issue by dkocher** [anosidium/Oliphaunt-Feedback-And-Support#25] opened 2024-03-23 12:03 UTC
### Description

It would be intuitive if the accounts are assigned a keyboard shortcut numbered like ⌘-1, ⌘-2, ….

**Comment by anosidium** [comment] 2024-03-23 17:37
This is a duplicate of https://github.com/anosidium/Oliphaunt-Feedback-And-Support/issues/4.

**Closed by anosidium** 2024-03-23 17:37 UTC
Labels: enhancement
